[package]
name = "p05-mob-in-the-middle"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
regex = "1.11.1"
tokio = { version = "1.47.1", features = ["full"] }

[dependencies.server]
path = "../server"